/rosrider_node:
  ros__parameters:
    # system parameters
    I2C_ENABLED: True
    ODOM_FRAME_ID: 'odom'
    BASE_FRAME_ID: 'base_footprint'
    BROADCAST_TF2: True
    PUB_ODOMETRY: True
    PUB_JOINTS: True
    PUB_DIAGNOSTICS: True
    ROS2RPI_CONFIG: 0x00 # 0x00 # 0x0F # 0x33
    I2C_ADDRESS: 0x3c
    DEBUG: False
    RTC_TRIM: 0x7FFF
    ALLOWED_SKIP: 3
    MONITOR_RATE: 100
    MAX_IDLE_SECONDS: 1800
    # driver configuration
    DRIVE_MODE: 3
    CONFIG_FLAGS: 112
    UPDATE_RATE: 20
    # pwm configuration
    PWM_DIV: 16
    PWM_SCALE: 256
    PWM_FRQ: 1000
    # motor configuration
    GEAR_RATIO: 65.0
    ENCODER_PPR: 48
    WHEEL_DIA: 0.0685
    BASE_WIDTH: 0.174
    MAX_RPM: 160.0
    # dead zones
    LEFT_FORWARD_DEADZONE: 12
    LEFT_REVERSE_DEADZONE: 12
    RIGHT_FORWARD_DEADZONE: 12
    RIGHT_REVERSE_DEADZONE: 12
    # pid configuration
    UPPER_LIMIT: 240
    LEFT_KP: 9.6
    LEFT_KI: 6.4
    LEFT_KD: 0.0
    RIGHT_KP: 9.6
    RIGHT_KI: 6.4
    RIGHT_KD: 0.0
    TANH_DIV: 2.0
    SIGM_DIV: 10.0
    K_FB_WINDUP: 0.5
    K_FF_VEL: 0.12
    K_FF_ACCEL: 0.08
    # cascaded loop
    INNER_LIMIT: 240
    CURRENT_KP: 9.6
    CURRENT_KI: 6.4
    CURRENT_MULTIPLIER_LEFT: 3.6
    CURRENT_MULTIPLIER_RIGHT: 3.6
    R_ARM: 2.0
    CURRENT_OMEGA_K_LEFT: 0.0
    CURRENT_OMEGA_K_RIGHT: 0.0
    # torque constant
    LEFT_KT: 0.016
    LEFT_KT_W: -0.008
    RIGHT_KT: 0.016
    RIGHT_KT_W: -0.008
    # stribeck friction
    STATIC_KICK: 0.8
    COULOMB_RUN: 0.2
    STRIBECK_WIDTH: 2.1
    VISCOUS_FRICTION: 0.064
    VISCOUS_FRICTION_LIMIT: 1.2
    EB_FF_LIMIT: 12.0
    SCV_OMEGA_THRESHOLD: 0.05
    SCV_LATCH_THRESHOLD: 1.0
    # electrical limits
    MAIN_AMP_LIMIT: 3.6
    BAT_VOLTS_HIGH: 15.0
    BAT_VOLTS_LOW: 6.0
    LEFT_AMP_LIMIT: 2.4
    RIGHT_AMP_LIMIT: 2.4
    INA219_CAL: 8192
    # calibration
    CS_LEFT_OFFSET: 0
    CS_RIGHT_OFFSET: 0
    # motor scope
    ADC_SPEED: 16000
    CS_WAVEFORM_DIV: 16
    # trim
    TRIM_GAIN: 1.0
    TRIM_MOTOR_K: 1.0
    TRIM_CONSTANT: 0.0
    # boolean parameters
    AUTO_SYNC: True
    ADC_SYNC: True
    CASCADED: True
    AUTO_BIAS: True
    ADC_MULTIPHASE: True
    ADC_BIPHASE: False
    OUTER_FEEDFORWARD: True
    OUTER_SCV: True
    VOLTAGE_FILTER: True
    AUTO_BRAKE: False
    BEMF_FILTERED_OMEGA: True
    PID_FILTERED_OMEGA: True
    SCV_FILTERED_OMEGA: True
    CROSS_COUPLED_CONTROL: True
    # filter configs
    OMEGA_FILTER_TYPE: 1
    CURRENT_FILTER_TYPE: 3
    OUTPUT_FILTER_TYPE: 0
    # sync
    SYNC_KP: 256
    SYNC_KI: 4
    SYNC_LIMIT: 1024
    DT_I2C: 64
    DT_THRESHOLD: 8
    # experimental
    CROSS_KP: 16.0
    CROSS_K_LEFT: 1.0
    CROSS_K_RIGHT: 1.0
    # topic paramters
    CMD_VEL_TOPIC: 'cmd_vel_nav'