/rosrider_node:
  ros__parameters:
    I2C_ENABLED: True
    ODOM_FRAME_ID: 'odom'
    BASE_FRAME_ID: 'base_footprint'
    BROADCAST_TF2: True
    PUB_ODOMETRY: True
    PUB_JOINTS: True
    PUB_DIAGNOSTICS: True
    ROS2RPI_CONFIG: 0x0F # 0x0F # 0x33
    AUTOSYNC: True
    DEBUG: False
    CONFIG_FLAGS: 48
    UPDATE_RATE: 20
    ALLOWED_SKIP: 3
    PWM_DIV: 16
    DRIVE_MODE: 3
    OUTPUT_FILTER_TYPE: 0
    MONITOR_RATE: 100
    PWM_SCALE: 256
    PWM_FRQ: 1000
    MAX_IDLE_SECONDS: 3600
    UPPER_LIMIT: 192
    INTEGRAL_LIMIT: 128
    ENCODER_PPR: 48
    RTC_TRIM: 0x7FFF
    LEFT_FORWARD_DEADZONE: 12
    LEFT_REVERSE_DEADZONE: 12
    RIGHT_FORWARD_DEADZONE: 12
    RIGHT_REVERSE_DEADZONE: 12
    GEAR_RATIO: 65.0
    WHEEL_DIA: 0.0685
    BASE_WIDTH: 0.174
    MAIN_AMP_LIMIT: 3.6
    BAT_VOLTS_HIGH: 15.0
    BAT_VOLTS_LOW: 6.0
    MAX_RPM: 160.0
    LEFT_AMP_LIMIT: 1.6
    RIGHT_AMP_LIMIT: 1.6
    LEFT_KP: 2.4
    LEFT_KI: 1.6
    LEFT_KD: 0.0
    RIGHT_KP: 2.4
    RIGHT_KI: 1.6
    RIGHT_KD: 0.0
    GAIN: 1.0
    TRIM: 0.0
    MOTOR_CONSTANT: 1.0
    I2C_ADDRESS: 0x3c
    ADCSYNC: True
    FASTADC: False
    CASCADED: False
    INA219_CAL: 11469
    TANH_DIV: 2.0
    SIGM_DIV: 10.0
    ADC_CS_DIV: 32
    CMD_VEL_TOPIC: 'cmd_vel'