/rosrider_node:
  ros__parameters:
    # system parameters
    I2C_ENABLED: True
    ODOM_FRAME_ID: 'odom'
    BASE_FRAME_ID: 'base_footprint'
    BROADCAST_TF2: True
    PUB_ODOMETRY: True
    PUB_JOINTS: True
    PUB_DIAGNOSTICS: True
    ROS2RPI_CONFIG: 0x00 # 0x00 # 0x0F # 0x33
    I2C_ADDRESS: 0x3c
    DEBUG: False
    RTC_TRIM: 0x7FFF
    ALLOWED_SKIP: 3
    MONITOR_RATE: 100
    MAX_IDLE_SECONDS: 1800
    # driver configuration
    DRIVE_MODE: 3
    CONFIG_FLAGS: 48
    UPDATE_RATE: 20
    # pwm configuration
    PWM_DIV: 16
    PWM_SCALE: 256
    PWM_FRQ: 1000
    # motor configuration
    GEAR_RATIO: 65.0
    ENCODER_PPR: 48
    WHEEL_DIA: 0.0685
    BASE_WIDTH: 0.174
    MAX_RPM: 160.0
    # dead zones
    LEFT_FORWARD_DEADZONE: 12
    LEFT_REVERSE_DEADZONE: 12
    RIGHT_FORWARD_DEADZONE: 12
    RIGHT_REVERSE_DEADZONE: 12
    # pid configuration
    UPPER_LIMIT: 160
    LEFT_KP: 2.2
    LEFT_KI: 1.6
    LEFT_KD: 0.0
    RIGHT_KP: 2.2
    RIGHT_KI: 1.6
    RIGHT_KD: 0.0
    TANH_DIV: 2.0
    SIGM_DIV: 10.0
    KB: 0.5
    K_FF_VEL: 0.64
    K_FF_ACCEL: 0.32
    # cascaded loop
    INNER_LIMIT: 160
    STATIC_KICK: 90
    COULOMB_RUN: 10
    OMEGA_STICTION_THRESHOLD: 10
    CURRENT_KP: 1.0
    CURRENT_KI: 1.0
    CURRENT_MULTIPLIER: 3.6
    TORQUE_CONSTANT: 0.015
    R_ARM: 2.0
    L_ARM: 0.001
    # filter configuration
    OUTPUT_FILTER_TYPE: 0
    INNER_FILTER_TYPE: 0
    # electrical
    MAIN_AMP_LIMIT: 3.6
    BAT_VOLTS_HIGH: 15.0
    BAT_VOLTS_LOW: 6.0
    LEFT_AMP_LIMIT: 1.6
    RIGHT_AMP_LIMIT: 1.6
    INA219_CAL: 8192
    # calibration
    CS_LEFT_OFFSET: 0
    CS_RIGHT_OFFSET: 0
    # motor scope
    ADC_SPEED: 16000
    CS_WAVEFORM_DIV: 16
    # trim
    GAIN: 1.0
    TRIM: 0.0
    MOTOR_CONSTANT: 1.0
    # boolean parameters
    AUTOSYNC: True
    ADCSYNC: True
    CASCADED: False
    BACKEMF: False
    CASCADE_FILTER: False
    AUTO_BIAS: True
    ADC_MULTIPHASE: False
    ADC_BIPHASE: False
    OUTER_FEEDFORWARD: False
    # topic paramters
    CMD_VEL_TOPIC: 'cmd_vel_nav'