/rosrider_node:
  ros__parameters:
    # system parameters
    I2C_ENABLED: True
    ODOM_FRAME_ID: 'odom'
    BASE_FRAME_ID: 'base_footprint'
    BROADCAST_TF2: True
    PUB_ODOMETRY: True
    PUB_JOINTS: True
    PUB_DIAGNOSTICS: True
    ROS2RPI_CONFIG: 0x33 # 0x00 # 0x0F # 0x33
    I2C_ADDRESS: 0x3c
    DEBUG: False
    RTC_TRIM: 0x7FFF
    ALLOWED_SKIP: 3
    MONITOR_RATE: 100
    MAX_IDLE_SECONDS: 1800
    # driver configuration
    DRIVE_MODE: 3
    CONFIG_FLAGS: 48
    UPDATE_RATE: 20
    # pwm configuration
    PWM_DIV: 32
    PWM_SCALE: 256
    PWM_FRQ: 100
    # motor configuration
    GEAR_RATIO: 45.0
    ENCODER_PPR: 12
    WHEEL_DIA: 0.0685
    BASE_WIDTH: 0.1
    MAX_RPM: 90.0
    # dead zones
    LEFT_FORWARD_DEADZONE: 8
    LEFT_REVERSE_DEADZONE: 8
    RIGHT_FORWARD_DEADZONE: 8
    RIGHT_REVERSE_DEADZONE: 8
    # pid configuration
    UPPER_LIMIT: 240
    LEFT_KP: 1.8
    LEFT_KI: 0.9
    LEFT_KD: 0.0
    RIGHT_KP: 1.8
    RIGHT_KI: 0.9
    RIGHT_KD: 0.0
    TANH_DIV: 2.0
    SIGM_DIV: 10.0
    K_FB_WINDUP: 0.5
    K_FF_VEL: 0.008
    K_FF_ACCEL: 0.008
    # cascaded loop
    INNER_LIMIT: 240
    CURRENT_KP: 1.0
    CURRENT_KI: 1.0
    CURRENT_MULTIPLIER_LEFT: 4.8
    CURRENT_MULTIPLIER_RIGHT: 4.8
    R_ARM: 2.0
    # torque constant
    LEFT_KT: 0.012
    LEFT_KT_W: -0.004
    RIGHT_KT: 0.012
    RIGHT_KT_W: -0.004
    # stribeck friction
    STATIC_KICK: 3.0
    COULOMB_RUN: 1.5
    STRIBECK_WIDTH: 8.0
    VISCOUS_FRICTION: 0.096
    VISCOUS_FRICTION_LIMIT: 1.2
    EB_FF_LIMIT: 12.0
    SCV_OMEGA_THRESHOLD: 0.05
    # electrical limits
    MAIN_AMP_LIMIT: 2.8
    BAT_VOLTS_HIGH: 15.0
    BAT_VOLTS_LOW: 6.0
    LEFT_AMP_LIMIT: 2.8
    RIGHT_AMP_LIMIT: 2.8
    INA219_CAL: 8192
    # calibration
    CS_LEFT_OFFSET: 0
    CS_RIGHT_OFFSET: 0
    # motor scope
    ADC_SPEED: 16000
    CS_WAVEFORM_DIV: 16
    # trim
    TRIM_GAIN: 1.0
    TRIM_MOTOR_K: 1.0
    TRIM_CONSTANT: 0.0
    # boolean parameters
    AUTO_SYNC: True
    ADC_SYNC: True
    CASCADED: False
    AUTO_BIAS: True
    ADC_MULTIPHASE: False
    ADC_BIPHASE: False
    OUTER_FEEDFORWARD: False
    OUTER_SCV: False
    VOLTAGE_FILTER: False
    AUTO_BRAKE: False
    BEMF_FILTERED_OMEGA: False
    PID_FILTERED_OMEGA: False
    SCV_FILTERED_OMEGA: False
    CROSS_COUPLED_CONTROL: False
    # filter configs
    OMEGA_FILTER_TYPE: 0
    CURRENT_FILTER_TYPE: 3
    OUTPUT_FILTER_TYPE: 0
    # experimental
    CROSS_KP: 16.0
    CROSS_K_LEFT: 1.0
    CROSS_K_RIGHT: 1.0
    # topic paramters
    CMD_VEL_TOPIC: 'cmd_vel'