/rosrider_node:
  ros__parameters:
    # system parameters
    I2C_ENABLED: True
    ODOM_FRAME_ID: 'odom'
    BASE_FRAME_ID: 'base_footprint'
    BROADCAST_TF2: True
    PUB_ODOMETRY: True
    PUB_JOINTS: True
    PUB_DIAGNOSTICS: True
    ROS2RPI_CONFIG: 0x00 # 0x00 # 0x0F # 0x33
    I2C_ADDRESS: 0x3c
    DEBUG: False
    RTC_TRIM: 0x7FFF
    ALLOWED_SKIP: 3
    MONITOR_RATE: 100
    MAX_IDLE_SECONDS: 1800
    # driver configuration
    DRIVE_MODE: 3
    CONFIG_FLAGS: 48
    UPDATE_RATE: 20
    # pwm configuration
    PWM_DIV: 32
    PWM_SCALE: 256
    PWM_FRQ: 100
    # motor configuration
    GEAR_RATIO: 45.0
    ENCODER_PPR: 12
    WHEEL_DIA: 0.0685
    BASE_WIDTH: 0.1
    MAX_RPM: 90.0
    # dead zones
    LEFT_FORWARD_DEADZONE: 8
    LEFT_REVERSE_DEADZONE: 8
    RIGHT_FORWARD_DEADZONE: 8
    RIGHT_REVERSE_DEADZONE: 8
    # pid configuration
    UPPER_LIMIT: 240
    LEFT_KP: 1.8
    LEFT_KI: 0.9
    LEFT_KD: 0.0
    RIGHT_KP: 1.8
    RIGHT_KI: 0.9
    RIGHT_KD: 0.0
    TANH_DIV: 2.0
    SIGM_DIV: 10.0
    K_FB_WINDUP: 0.5
    K_FF_VEL: 0.08
    K_FF_ACCEL: 0.16
    # cascaded loop
    INNER_LIMIT: 240
    CURRENT_KP: 1.0
    CURRENT_KI: 1.0
    CURRENT_MULTIPLIER: 4.8
    TORQUE_CONSTANT: 0.016
    R_ARM: 2.0
    L_ARM: 0.0015
    IR_COMP_GAIN: 2.0
    # stribeck friction
    STATIC_KICK: 6.0
    COULOMB_RUN: 3.0
    STRIBECK_WIDTH: 64.0
    VISCOUS_FRICTION: 0.001
    VISCOUS_FRICTION_LIMIT: 1.2
    EB_FF_LIMIT: 12.0
    # filter configuration
    OUTPUT_FILTER_TYPE: 0
    # electrical limits
    MAIN_AMP_LIMIT: 2.8
    BAT_VOLTS_HIGH: 15.0
    BAT_VOLTS_LOW: 6.0
    LEFT_AMP_LIMIT: 1.2
    RIGHT_AMP_LIMIT: 1.2
    INA219_CAL: 8192
    # calibration
    CS_LEFT_OFFSET: 0
    CS_RIGHT_OFFSET: 0
    # motor scope
    ADC_SPEED: 16000
    CS_WAVEFORM_DIV: 16
    # trim
    GAIN: 1.0
    TRIM: 0.0
    MOTOR_CONSTANT: 1.0
    # boolean parameters
    AUTO_SYNC: True
    ADC_SYNC: True
    CASCADED: False
    IR_COMP: False
    CASCADE_FILTER: False
    AUTO_BIAS: True
    ADC_MULTIPHASE: True
    ADC_BIPHASE: False
    OUTER_FEEDFORWARD: True
    OMEGA_FILTER: False
    VOLTAGE_FILTER: False
    AUTO_BRAKE: False
    INDUCTIVE_COMP: True
    # outer friction model - if True, dead zones are ignored, and stribeck friction model will be used
    OUTER_SCV: False
    # topic paramters
    CMD_VEL_TOPIC: 'cmd_vel'