camera:
  v4l2_camera_node:
    ros__parameters:
      video_device: /dev/video0
      pixel_format: YUYV
      output_encoding: rgb8
      image_size: [640, 480]
      time_per_frame: [1, 10]
      frame_rate: 10
      camera_frame_id: camera_optical_frame
      disable_pub_plugins:
        - image_transport/compressedDepth
