camera:
  v4l2_camera_node:
    ros__parameters:
      video_device: /dev/video0
      pixel_format: YUYV
      output_encoding: yuv422_yuy2
      image_size: [320, 240]
      time_per_frame: [1, 30]
      camera_frame_id: camera_optical_frame
